/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddedOriginalTracksList: typeof import('./src/components/CreateTrack/AddedOriginalTracksList.vue')['default']
    AddedTagsList: typeof import('./src/components/CreateTrack/AddedTagsList.vue')['default']
    AppNav: typeof import('./src/components/AppNav.vue')['default']
    Autocomplete: typeof import('primevue/autocomplete')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    BackButton: typeof import('./src/components/BackButton.vue')['default']
    BaseInfoEdit: typeof import('./src/components/CreateTrack/BaseInfoEdit.vue')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    ConfirmPopup: typeof import('primevue/confirmpopup')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Layout: typeof import('./src/components/CreateTrack/Layout.vue')['default']
    NewTagInput: typeof import('./src/components/CreateTrack/NewTagInput.vue')['default']
    OriginalsEdit: typeof import('./src/components/CreateTrack/OriginalsEdit.vue')['default']
    PlatformLinkList: typeof import('./src/components/PlatformLinkList.vue')['default']
    PlatformTab: typeof import('./src/components/CreateTrack/PlatformTab.vue')['default']
    PlatformTabList: typeof import('./src/components/CreateTrack/PlatformTabList.vue')['default']
    PlatformTrackSearch: typeof import('./src/components/CreateTrack/PlatformTrackSearch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    TagsEdit: typeof import('./src/components/CreateTrack/TagsEdit.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    TrackItem: typeof import('./src/components/TrackItem.vue')['default']
  }
}
