/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddedTagsList: typeof import('./src/components/CreateTrack/AddedTagsList.vue')['default']
    AppNav: typeof import('./src/components/AppNav.vue')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    BackButton: typeof import('./src/components/BackButton.vue')['default']
    BaseInfoEdit: typeof import('./src/components/CreateTrack/BaseInfoEdit.vue')['default']
    BaseLayout: typeof import('./src/components/BaseLayout.vue')['default']
    BaseTrackItem: typeof import('./src/components/BaseTrackItem.vue')['default']
    Branding: typeof import('./src/components/header/Branding.vue')['default']
    ConfirmPopup: typeof import('primevue/confirmpopup')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MixedTrackForNewMix: typeof import('./src/components/MixedTrackForNewMix.vue')['default']
    MixedTrackList: typeof import('./src/components/track-page/MixedTrackList.vue')['default']
    Navigation: typeof import('./src/components/header/Navigation.vue')['default']
    NewTagInput: typeof import('./src/components/CreateTrack/NewTagInput.vue')['default']
    OriginalsEdit: typeof import('./src/components/CreateTrack/OriginalsEdit.vue')['default']
    PlatformLinkList: typeof import('./src/components/new-mix/PlatformLinkList.vue')['default']
    PlatformLinkListItem: typeof import('./src/components/new-mix/PlatformLinkListItem.vue')['default']
    PlatformTab: typeof import('./src/components/CreateTrack/PlatformTab.vue')['default']
    PlatformTabList: typeof import('./src/components/CreateTrack/PlatformTabList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/track-list/SearchBar.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    TagsEdit: typeof import('./src/components/CreateTrack/TagsEdit.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    TrackInfo: typeof import('./src/components/track-page/TrackInfo.vue')['default']
    TrackItem: typeof import('./src/components/TrackItem.vue')['default']
  }
}
