/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppNav: typeof import('./src/components/AppNav.vue')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    BackButton: typeof import('./src/components/BackButton.vue')['default']
    Chip: typeof import('primevue/chip')['default']
    ConfirmPopup: typeof import('primevue/confirmpopup')['default']
    PlatformLinkList: typeof import('./src/components/PlatformLinkList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    TrackItem: typeof import('./src/components/TrackItem.vue')['default']
  }
}
