FROM node:alpine AS build

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm i --frozen-lockfile

COPY . .

RUN echo VITE_BASE_API_URL

CMD ["sh", "-c", "pnpm dev --port ${FRONTEND_PORT}"]
