services:
  frontend:
    build: ./frontend
    container_name: mixup-frontend
    volumes:
      - ./certs:/etc/nginx/certs
    environment:
      - NODE_ENV=production
      - VITE_BASE_API_URL=${VITE_BASE_API_URL}
      - BACKEND_PORT=${BACKEND_PORT}
    networks:
      - mixup-net
    ports:
      - 80:80
      - 443:443
  backend:
    build: ./backend-hono
    container_name: mixup-backend
    environment:
      - NODE_ENV=production
      - BACKEND_PORT=${BACKEND_PORT}
    networks:
      - mixup-net
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}

networks:
  mixup-net:
