services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: mixup-frontend
    environment:
      - NODE_ENV=development
      - VITE_BASE_API_URL=${VITE_BASE_API_URL}
      - BACKEND_PORT=${BACKEND_PORT}
      - FRONTEND_PORT=${FRONTEND_PORT}
    networks:
      - mixup-net
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
  backend:
    build: ./backend-hono
    container_name: mixup-backend
    environment:
      - NODE_ENV=development
      - BACKEND_PORT=${BACKEND_PORT}
    networks:
      - mixup-net
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}

networks:
  mixup-net:
