services:
  frontend:
    build: ./frontend
    container_name: mixup-frontend
    volumes:
      - ./certs:/etc/nginx/certs
    environment:
      - NODE_ENV=production
      - VITE_BASE_API_URL=${VITE_BASE_API_URL}
      - BACKEND_PORT=${BACKEND_PORT}
    networks:
      - mixup-net
    ports:
      - 80:80
      - 443:443
  backend:
    build: ./backend-hono
    container_name: mixup-backend
    environment:
      - NODE_ENV=production
      - BACKEND_PORT=${BACKEND_PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - PROXY_URL=${PROXY_URL}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - YOUTUBE_KEY=${YOUTUBE_KEY}

    networks:
      - mixup-net
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db
    networks:
      - mixup-net

networks:
  mixup-net:

volumes:
  dbdata:
