events {}

http {

		include /etc/nginx/mime.types;

		root /etc/nginx/html;

    server {
        listen 80;
        # server_name mixup.space;

        location / {
						try_files $uri $uri/ /index.html;
            # return 301 https://$host$request_uri;
        }
    }

    # server {
    # 		listen 443 ssl;
    #     server_name mixup.space;

    #     ssl_certificate /etc/nginx/certs/fullchain.pem;
    #     ssl_certificate_key /etc/nginx/certs/privkey.pem;

		# 		location / {
    #     		try_files $uri $uri/ /index.html;
    # 		}

    #     location /api/ {
		# 				proxy_pass https://mixup.space:4000;
		# 				proxy_set_header Host $host;
		# 				proxy_set_header X-Real-IP $remote_addr;
		# 				proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     		proxy_set_header X-Forwarded-Proto $scheme;
    #     }
    # }
}
