name: Deploy

on:
  push:
    branches:
      - main

jobs:
  prepare-environment:
      runs-on: self-hosted
      steps:
        - name: Stop and remove containers, networks
          run: docker-compose down
        - name: Remove unused data
          run: docker system prune -a -f

  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Docker Compose
        run: |
          docker compose up -d
