name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: runner-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Docker Compose
        run: |
          docker-compose up -d --build
